### ISSUE TITLE
Elasticsearch rejects geometries

### ISSUE THREAD

**Issue by rutgervanwilligen** [histograph/core#19]
See https://gist.github.com/rutgervanwilligen/5bc20ee44e839d7ca4a2 for a list of rejected geometries, including the reasons of rejection and a sample geometry.
- [x] Gemeentegeschiedenis: Find cause
  - Found! Several wrongly formatted geometries. Source has provided new geometries.
- [x] Gemeentegeschiedenis: Import new geometries and check if they're fixed.
- [x] Atlas-verstedelijking: Find cause
  - Found: Multipolygons with self-intersecting points
- [ ] Atlas-verstedelijking: Fix polygons ( @reinvantveer is working on it) and import
- [x] Gewesten: Find cause
  - Found: Self intersecting polygons
- [ ] Gewesten: Fix and reimport

**Comment by rutgervanwilligen** [comment]
Gemeentegeschiedenis/106 contains a syntactically correct GeoJSON geometry, but is not valid. 

http://bl.ocks.org/d/5334d09b72d09c940730

The geometry is formatted as a single polygon, but this contains two islands. Syntactically speaking, the second 'island' in the polygon array is interpreted as a hole in the first, instead of a second island.

**Comment by reinvantveer** [comment]
Should geometries be OGC-simple feature specification valid? This could ve checked during conversion if checking at the source is the preferred solution.

Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Rutger van Willigen notifications@github.com
Datum:11-03-2015 14:54 (GMT+01:00)
Aan: histograph/core core@noreply.github.com
Cc:
Onderwerp: Re: [core] Elasticsearch rejects geometries (#19)

Gemeentegeschiedenis/106 contains a syntactically correct GeoJSON geometry, but is not valid.

http://bl.ocks.org/d/5334d09b72d09c940730

The geometry is formatted as a single polygon, but this contains two islands. Syntactically speaking, the second 'island' in the polygon array is interpreted as a hole in the first, instead of a second.

**Comment by reinvantveer** [comment]
So often, the geometry type should be multipolygon, not polygon?

Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Rutger van Willigen notifications@github.com
Datum:11-03-2015 12:58 (GMT+01:00)
Aan: histograph/core core@noreply.github.com
Cc:
Onderwerp: [core] Elasticsearch rejects geometries (#19)

See https://gist.github.com/rutgervanwilligen/5bc20ee44e839d7ca4a2 for a list of rejected geometries, including the reasons of rejection and a sample geometry.

**Comment by rutgervanwilligen** [comment]
All of the Gemeentegeschiedenis geometries are now accepted.

**Comment by reinvantveer** [comment]
:+1:

**Comment by mmmenno** [comment]
:-)

**Comment by reinvantveer** [comment]
## PostGIS valid geometries are sometimes rejected by Elasticsearch shape indexer

See also:
[this link](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/geo/builders/BasePolygonBuilder.java#L358)

Elasticsearch has (custom?) geometry checking procedure using Java Topology Suite and Spatial4j:

```
import com.spatial4j.core.shape.Shape;
import com.vividsolutions.jts.geom.*;
```

From [here](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/geo/builders/BasePolygonBuilder.java#L22)

Node conversion scripts need similar checking for the geometries to be inserted I suppose.

**Comment by reinvantveer** [comment]
Perhaps use [this](http://docs.qgis.org/2.0/nl/docs/user_manual/plugins/plugins_topology_checker.html)

**Comment by wires** [comment]
kapotte geometrieren op andere queue zetten?

**Comment by jobspierings** [comment]
@bertspaan zegt:

> heeft te maken met strengheid van Lucene. Meeste gefixed - nieuwe issues aanmaken als tegenkomen.
