### ISSUE TITLE
killed core mid-process, error 'cannot perform data updates in a transaction that has performed schema updates'

### ISSUE THREAD

**Issue by ghost** [histograph/core#49]
you guys are awesome.

I accidentally killed core in the middle of an import. Now it doesn't seem to pick up new imports. It reports this java error every time I start up, and no new objects are pushed to the queue:

```
dev@hg2:~/histograph/core$ node index.js -verbose
   ●───────●    
  /║       ║\  
 / ║       ║ \ 
●  ║═══════║  ● 
 \ ║       ║ / 
  \║       ║/  
   ●───────●    
writing
send end
data
recv end 9352
size { duration_ms: 6.743625,
  statusCode: 200,
  errors: 
   [ { code: 'Neo.DatabaseError.Statement.ExecutionFailure',
       message: 'Cannot perform data updates in a transaction that has performed schema updates.',
```

I followed the instructions for [cleaning up](https://github.com/histograph/core#cleaning-up-before--after-running) before/after running but it seems like I haven't properly reset things.

any advice on what more I need to do?

**Comment by ghost** [comment]
I think I found it: clearing the redis queue did the trick.

```
$ redis-cli
> FLUSHALL
```

Maybe add that to README?

**Comment by wires** [comment]
this was actually due to automatically creating the schema's in the same transaction as other operations. 

I disabled it a little while ago, it needs another fix, 
indeed clearing redis queue works, because then the schema creation operation timed out and is run in it's own transaction.. (instead of being batched up with messages from redis queue).

Will look for a good solution for this
https://github.com/graphmalizer/graphmalizer-core/issues/13 

thanks for reporting
